import { BadGatewayException, Injectable, Logger } from "@nestjs/common";

export interface TenantMpesaCredentials {
  mpesaConsumerKey: string;
  mpesaConsumerSecretEncrypted: string;
  mpesaPasskeyEncrypted: string;
  shortcode: string;
}

/**
 * Payouts deliberately do NOT carry the passkey. It exists solely to build the STK
 * Push `Password` (see generatePassword); B2C authenticates with the initiator name
 * and security credential instead. Keeping it out of this type means the payout path
 * never decrypts a secret it has no use for.
 *
 * securityCredential is the value Safaricom's Daraja portal emits — the initiator
 * password ALREADY RSA-encrypted against their public certificate. ScriptPay stores
 * it AES-256-GCM-encrypted at rest and passes it through verbatim; it never sees the
 * underlying password and holds no Safaricom certificate. See schema.prisma's comment
 * on Tenant.mpesaSecurityCredentialEncrypted for why that division was chosen.
 */
export interface TenantPayoutCredentials {
  mpesaConsumerKey: string;
  mpesaConsumerSecretEncrypted: string;
  shortcode: string;
  initiatorName: string;
  securityCredential: string;
}

/** Only the fields OAuth actually needs — shared by the collection and payout paths. */
type OAuthCredentials = Pick<TenantMpesaCredentials, "mpesaConsumerKey" | "mpesaConsumerSecretEncrypted">;

/**
 * BusinessPayment is an ordinary merchant-to-customer disbursement (a refund, a
 * withdrawal). SalaryPayment and PromotionPayment are Safaricom's separately
 * registered variants — they differ in the receiving customer's registration
 * requirements and in Safaricom's own charge tariff, not in the request shape.
 */
export type B2cCommandId = "BusinessPayment" | "SalaryPayment" | "PromotionPayment";

interface B2cParams {
  /**
   * Generated by the CALLER before this request goes out — unlike STK Push, whose
   * CheckoutRequestID only comes back in Daraja's response. That ordering is what
   * lets a payout survive a timed-out request: the row can still be correlated to
   * the result callback that eventually arrives.
   */
  originatorConversationId: string;
  amount: number;
  msisdn: string;
  commandId: B2cCommandId;
  remarks: string;
  occasion?: string;
}

interface B2cResponse {
  ConversationID: string;
  OriginatorConversationID: string;
  ResponseCode: string;
}

interface StkPushParams {
  amount: number;
  msisdn: string;
  accountReference: string;
  transactionDesc: string;
  transactionType: "CustomerPayBillOnline" | "CustomerBuyGoodsOnline";
}

interface StkPushResponse {
  MerchantRequestID: string;
  CheckoutRequestID: string;
  ResponseCode: string;
}

interface CachedToken {
  token: string;
  expiresAt: number;
}

@Injectable()
export class DarajaClient {
  private readonly logger = new Logger(DarajaClient.name);
  // Keyed by consumerKey — each tenant's credentials get their own cached token,
  // since tokens are only valid for the credentials that requested them.
  private tokenCache = new Map<string, CachedToken>();

  private get baseUrl(): string {
    return process.env.MPESA_ENV === "production" ? "https://api.safaricom.co.ke" : "https://sandbox.safaricom.co.ke";
  }

  private async getAccessToken(creds: OAuthCredentials): Promise<string> {
    const now = Date.now();
    const cached = this.tokenCache.get(creds.mpesaConsumerKey);
    if (cached && cached.expiresAt > now) return cached.token;

    const credentials = Buffer.from(`${creds.mpesaConsumerKey}:${creds.mpesaConsumerSecretEncrypted}`).toString(
      "base64",
    );
    const response = await fetch(`${this.baseUrl}/oauth/v1/generate?grant_type=client_credentials`, {
      method: "GET",
      headers: { Authorization: `Basic ${credentials}` },
    });

    if (!response.ok) {
      const body = await response.text();
      this.logger.error(`Daraja OAuth token request failed: ${response.status} ${body}`);
      // A BadGatewayException (not a plain Error) so this reaches the caller as a real
      // HTTP error the frontend can display, instead of being swallowed into the global
      // filter's generic "Internal server error" — see docs/decisions.md if this pattern
      // gets extended further.
      throw new BadGatewayException("Failed to authenticate with Daraja using this tenant's credentials");
    }

    const data = (await response.json()) as { access_token: string; expires_in: string };
    const ttlMs = (Number(data.expires_in) - 60) * 1000;
    this.tokenCache.set(creds.mpesaConsumerKey, { token: data.access_token, expiresAt: now + ttlMs });
    return data.access_token;
  }

  private generatePassword(creds: TenantMpesaCredentials): { password: string; timestamp: string } {
    const timestamp = new Date()
      .toISOString()
      .replace(/[^0-9]/g, "")
      .slice(0, 14);
    const password = Buffer.from(`${creds.shortcode}${creds.mpesaPasskeyEncrypted}${timestamp}`).toString("base64");
    return { password, timestamp };
  }

  async initiateStkPush(creds: TenantMpesaCredentials, params: StkPushParams): Promise<StkPushResponse> {
    const accessToken = await this.getAccessToken(creds);
    const { password, timestamp } = this.generatePassword(creds);
    const callbackBaseUrl = process.env.MPESA_CALLBACK_BASE_URL;

    const response = await fetch(`${this.baseUrl}/mpesa/stkpush/v1/processrequest`, {
      method: "POST",
      headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        BusinessShortCode: creds.shortcode,
        Password: password,
        Timestamp: timestamp,
        TransactionType: params.transactionType,
        Amount: Math.round(params.amount),
        PartyA: params.msisdn,
        PartyB: creds.shortcode,
        PhoneNumber: params.msisdn,
        CallBackURL: `${callbackBaseUrl}/v1/webhooks/daraja/stk-callback`,
        AccountReference: params.accountReference,
        TransactionDesc: params.transactionDesc,
      }),
    });

    const body = await response.json();
    if (!response.ok || body.ResponseCode !== "0") {
      this.logger.error(`Daraja STK push rejected: ${JSON.stringify(body)}`);
      // Safaricom's own rejection reason (e.g. "Invalid TransactionType", "Invalid
      // CallBackURL") is safe to surface directly — it describes this tenant's own
      // request, not another tenant's data — and is far more actionable than the
      // generic 500 a plain Error would collapse into via the global exception filter.
      throw new BadGatewayException(
        body.errorMessage ?? body.ResponseDescription ?? "Daraja rejected the STK push request",
      );
    }

    return {
      MerchantRequestID: body.MerchantRequestID,
      CheckoutRequestID: body.CheckoutRequestID,
      ResponseCode: body.ResponseCode,
    };
  }

  /**
   * Outbound payout: shortcode -> customer handset.
   *
   * Two structural differences from initiateStkPush worth holding onto:
   *
   * 1. A "0" ResponseCode here means Safaricom ACCEPTED THE REQUEST INTO ITS QUEUE,
   *    not that money moved. The actual outcome arrives asynchronously at ResultURL.
   *    Nothing in this method's success path should ever be read as "the payout
   *    succeeded" — it means "the payout is now in flight."
   * 2. There are two callback URLs, not one. QueueTimeOutURL fires when Safaricom
   *    can't process the request in time; it explicitly does NOT mean the payout
   *    failed, and the handler for it must not release the reservation (see the
   *    b2c-timeout route).
   */
  async initiateB2C(creds: TenantPayoutCredentials, params: B2cParams): Promise<B2cResponse> {
    const accessToken = await this.getAccessToken(creds);
    const callbackBaseUrl = process.env.MPESA_CALLBACK_BASE_URL;

    const response = await fetch(`${this.baseUrl}/mpesa/b2c/v3/paymentrequest`, {
      method: "POST",
      headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        OriginatorConversationID: params.originatorConversationId,
        InitiatorName: creds.initiatorName,
        SecurityCredential: creds.securityCredential,
        CommandID: params.commandId,
        Amount: Math.round(params.amount),
        // PartyA is the paying shortcode and PartyB the receiving handset — the exact
        // reverse of the STK push above, where the customer is PartyA. Getting these
        // backwards is the single easiest mistake to make when adapting one to the other.
        PartyA: creds.shortcode,
        PartyB: params.msisdn,
        Remarks: params.remarks,
        QueueTimeOutURL: `${callbackBaseUrl}/v1/webhooks/daraja/b2c-timeout`,
        ResultURL: `${callbackBaseUrl}/v1/webhooks/daraja/b2c-result`,
        Occasion: params.occasion ?? "",
      }),
    });

    const body = await response.json();
    if (!response.ok || body.ResponseCode !== "0") {
      this.logger.error(`Daraja B2C request rejected: ${JSON.stringify(body)}`);
      // Same reasoning as initiateStkPush: Safaricom's rejection describes this
      // tenant's own request ("Invalid Initiator Information", "The initiator
      // information is invalid"), never another tenant's data, and is far more
      // actionable than the generic 500 a plain Error would collapse into.
      throw new BadGatewayException(
        body.errorMessage ?? body.ResponseDescription ?? "Daraja rejected the B2C payment request",
      );
    }

    return {
      ConversationID: body.ConversationID,
      // Echoed back by Safaricom. Returned rather than assumed so the caller can
      // assert it matches what it sent, if it ever wants to.
      OriginatorConversationID: body.OriginatorConversationID,
      ResponseCode: body.ResponseCode,
    };
  }

  async queryStkPushStatus(
    creds: TenantMpesaCredentials,
    checkoutRequestId: string,
  ): Promise<{ resultCode: number; resultDesc?: string }> {
    const accessToken = await this.getAccessToken(creds);
    const { password, timestamp } = this.generatePassword(creds);

    const response = await fetch(`${this.baseUrl}/mpesa/stkpushquery/v1/query`, {
      method: "POST",
      headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        BusinessShortCode: creds.shortcode,
        Password: password,
        Timestamp: timestamp,
        CheckoutRequestID: checkoutRequestId,
      }),
    });

    const body = await response.json();
    return { resultCode: Number(body.ResultCode ?? -1), resultDesc: body.ResultDesc };
  }
}
