import { BadGatewayException, Injectable, Logger } from "@nestjs/common";

export interface TenantMpesaCredentials {
  mpesaConsumerKey: string;
  mpesaConsumerSecretEncrypted: string;
  mpesaPasskeyEncrypted: string;
  shortcode: string;
}

/**
 * Payouts deliberately do NOT carry the passkey. It exists solely to build the STK
 * Push `Password` (see generatePassword); B2C authenticates with the initiator name
 * and security credential instead. Keeping it out of this type means the payout path
 * never decrypts a secret it has no use for.
 *
 * securityCredential is the value Safaricom's Daraja portal emits — the initiator
 * password ALREADY RSA-encrypted against their public certificate. ScriptPay stores
 * it AES-256-GCM-encrypted at rest and passes it through verbatim; it never sees the
 * underlying password and holds no Safaricom certificate. See schema.prisma's comment
 * on Tenant.mpesaSecurityCredentialEncrypted for why that division was chosen.
 */
export interface TenantPayoutCredentials {
  mpesaConsumerKey: string;
  mpesaConsumerSecretEncrypted: string;
  shortcode: string;
  initiatorName: string;
  securityCredential: string;
}

/** Only the fields OAuth actually needs — shared by the collection and payout paths. */
export type DarajaAuthCredentials = Pick<TenantMpesaCredentials, "mpesaConsumerKey" | "mpesaConsumerSecretEncrypted">;

export interface C2bUrlRegistrationCredentials extends DarajaAuthCredentials {
  shortcode: string;
}

/**
 * BusinessPayment is an ordinary merchant-to-customer disbursement (a refund, a
 * withdrawal). SalaryPayment and PromotionPayment are Safaricom's separately
 * registered variants — they differ in the receiving customer's registration
 * requirements and in Safaricom's own charge tariff, not in the request shape.
 */
export type B2cCommandId = "BusinessPayment" | "SalaryPayment" | "PromotionPayment";

interface B2cParams {
  /**
   * Generated by the CALLER before this request goes out — unlike STK Push, whose
   * CheckoutRequestID only comes back in Daraja's response. That ordering is what
   * lets a payout survive a timed-out request: the row can still be correlated to
   * the result callback that eventually arrives.
   */
  originatorConversationId: string;
  amount: number;
  msisdn: string;
  commandId: B2cCommandId;
  remarks: string;
  occasion?: string;
}

interface B2cResponse {
  ConversationID: string;
  OriginatorConversationID: string;
  ResponseCode: string;
}

interface StkPushParams {
  amount: number;
  msisdn: string;
  accountReference: string;
  transactionDesc: string;
  transactionType: "CustomerPayBillOnline" | "CustomerBuyGoodsOnline";
}

interface StkPushResponse {
  MerchantRequestID: string;
  CheckoutRequestID: string;
  ResponseCode: string;
}

interface CachedToken {
  token: string;
  expiresAt: number;
}

/**
 * The answer to "what happened to this STK push?", which has THREE outcomes, not two.
 *
 * `resultCode: null` is the third: Safaricom was asked and did not give a verdict.
 * That happens routinely — a push still awaiting the customer's PIN comes back as
 * HTTP 500 with `errorCode: "500.001.1001"` ("The transaction is being processed")
 * and no `ResultCode` field at all — and it is emphatically NOT a failure.
 *
 * This type exists because the previous shape (`resultCode: number`, defaulted via
 * `Number(body.ResultCode ?? -1)`) could not express it: every unknown collapsed to
 * -1, DriftDetectorService read "not zero" as "failed", and marked a push FAILED
 * while the customer was still holding their phone. FAILED is terminal in
 * ALLOWED_TRANSITIONS, so the genuine success callback arriving moments later could
 * never settle the row — the customer paid and the tenant was never credited.
 */
export interface StkPushStatusResult {
  /** Safaricom's terminal ResultCode, or null when they have not given a verdict. */
  resultCode: number | null;
  resultDesc?: string;
  /** Daraja's own errorCode when the QUERY was rejected or deferred, e.g. 500.001.1001. */
  errorCode?: string;
}

@Injectable()
export class DarajaClient {
  private readonly logger = new Logger(DarajaClient.name);
  // Keyed by consumerKey — each tenant's credentials get their own cached token,
  // since tokens are only valid for the credentials that requested them.
  private tokenCache = new Map<string, CachedToken>();

  private get baseUrl(): string {
    return process.env.MPESA_ENV === "production" ? "https://api.safaricom.co.ke" : "https://sandbox.safaricom.co.ke";
  }

  /**
   * Every Daraja call below expects a JSON body, but a request that never actually
   * reaches Daraja's own application layer — blocked by Safaricom's API gateway
   * (rate limiting, a locked initiator, an outage) — comes back as an HTML fault
   * page instead. Calling response.json() directly on that throws a raw
   * SyntaxError that bypasses every BadGatewayException below and reaches
   * HttpExceptionFilter as an unhandled 500, telling the caller nothing about
   * what actually happened. Reading as text first and parsing ourselves turns
   * that into the same clean, logged BadGatewayException every other rejection
   * here already produces.
   */
  private async parseDarajaJson(response: Response, context: string): Promise<any> {
    const raw = await response.text();
    try {
      return JSON.parse(raw);
    } catch {
      this.logger.error(`Daraja ${context} returned a non-JSON response (status ${response.status}): ${raw.slice(0, 500)}`);
      throw new BadGatewayException(
        `Daraja's ${context} endpoint returned an unexpected response — the request may have been blocked before reaching Daraja (rate limiting, a locked initiator, or an outage)`,
      );
    }
  }

  private async getAccessToken(creds: DarajaAuthCredentials): Promise<string> {
    const now = Date.now();
    const cached = this.tokenCache.get(creds.mpesaConsumerKey);
    if (cached && cached.expiresAt > now) return cached.token;

    const credentials = Buffer.from(`${creds.mpesaConsumerKey}:${creds.mpesaConsumerSecretEncrypted}`).toString(
      "base64",
    );
    const response = await fetch(`${this.baseUrl}/oauth/v1/generate?grant_type=client_credentials`, {
      method: "GET",
      headers: { Authorization: `Basic ${credentials}` },
    });

    if (!response.ok) {
      const body = await response.text();
      this.logger.error(`Daraja OAuth token request failed: ${response.status} ${body}`);
      // A BadGatewayException (not a plain Error) so this reaches the caller as a real
      // HTTP error the frontend can display, instead of being swallowed into the global
      // filter's generic "Internal server error" — see docs/decisions.md if this pattern
      // gets extended further. Safaricom's own reason is appended (truncated) rather than
      // left server-log-only, same as every other rejection in this file — this exact
      // message is what StkPushSection/B2cPayoutSection show the merchant via
      // transaction.failureReason, so a bare "failed to authenticate" told them nothing
      // about whether it was a wrong key, an expired app, or a rate limit.
      throw new BadGatewayException(
        `Failed to authenticate with Daraja using this tenant's credentials (Safaricom returned ${response.status}: ${body.slice(0, 300)})`,
      );
    }

    const data = (await this.parseDarajaJson(response, "OAuth token")) as { access_token: string; expires_in: string };
    const ttlMs = (Number(data.expires_in) - 60) * 1000;
    this.tokenCache.set(creds.mpesaConsumerKey, { token: data.access_token, expiresAt: now + ttlMs });
    return data.access_token;
  }

  /**
   * Builds a Daraja-facing callback URL with the shared webhook secret attached as
   * `?token=` — checked by DarajaWebhookSecretGuard on receipt. Daraja doesn't sign
   * its payloads, so this is what lets the webhook controller reject a forged
   * callback from anyone who discovers the bare path.
   */
  private buildWebhookUrl(path: string): string {
    const base = process.env.MPESA_CALLBACK_BASE_URL;
    const token = encodeURIComponent(process.env.DARAJA_WEBHOOK_SECRET ?? "");
    return `${base}/v1/webhooks/daraja/${path}?token=${token}`;
  }

  /**
   * Daraja's `Amount` is in whole shillings. Callers reach it by dividing
   * `amountMinorUnits` by 100, so a minor-unit amount that isn't a multiple of 100
   * arrives here as a fraction.
   *
   * This used to be `Math.round(params.amount)`, which quietly changed the figure:
   * 150 minor units became `1.5` became a real KES 2 charge, while the transaction
   * row and every ledger entry still said 150. The books and the money disagreed
   * and nothing anywhere reported it. The DTOs now reject such an amount up front
   * (`.multipleOf(100)`); this is the second line of defence, and it throws rather
   * than rounds — the callers already treat a throw here correctly (StkPushService
   * marks the transaction FAILED, B2cService additionally releases the reservation),
   * so failing loudly costs nothing and mis-charging costs real money.
   */
  private assertWholeShillings(amount: number, context: string): number {
    if (!Number.isInteger(amount)) {
      throw new Error(
        `Refusing to send a fractional amount to Daraja ${context}: ${amount} KES. ` +
          `M-Pesa settles in whole shillings, so amountMinorUnits must be a multiple of 100.`,
      );
    }
    return amount;
  }

  private generatePassword(creds: TenantMpesaCredentials): { password: string; timestamp: string } {
    const timestamp = new Date()
      .toISOString()
      .replace(/[^0-9]/g, "")
      .slice(0, 14);
    const password = Buffer.from(`${creds.shortcode}${creds.mpesaPasskeyEncrypted}${timestamp}`).toString("base64");
    return { password, timestamp };
  }

  async initiateStkPush(creds: TenantMpesaCredentials, params: StkPushParams): Promise<StkPushResponse> {
    const accessToken = await this.getAccessToken(creds);
    const { password, timestamp } = this.generatePassword(creds);

    const response = await fetch(`${this.baseUrl}/mpesa/stkpush/v1/processrequest`, {
      method: "POST",
      headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        BusinessShortCode: creds.shortcode,
        Password: password,
        Timestamp: timestamp,
        TransactionType: params.transactionType,
        Amount: this.assertWholeShillings(params.amount, "for an STK push"),
        PartyA: params.msisdn,
        PartyB: creds.shortcode,
        PhoneNumber: params.msisdn,
        CallBackURL: this.buildWebhookUrl("stk-callback"),
        AccountReference: params.accountReference,
        TransactionDesc: params.transactionDesc,
      }),
    });

    const body = await this.parseDarajaJson(response, "STK push");
    if (!response.ok || body.ResponseCode !== "0") {
      this.logger.error(`Daraja STK push rejected: ${JSON.stringify(body)}`);
      // Safaricom's own rejection reason (e.g. "Invalid TransactionType", "Invalid
      // CallBackURL") is safe to surface directly — it describes this tenant's own
      // request, not another tenant's data — and is far more actionable than the
      // generic 500 a plain Error would collapse into via the global exception filter.
      throw new BadGatewayException(
        body.errorMessage ?? body.ResponseDescription ?? "Daraja rejected the STK push request",
      );
    }

    return {
      MerchantRequestID: body.MerchantRequestID,
      CheckoutRequestID: body.CheckoutRequestID,
      ResponseCode: body.ResponseCode,
    };
  }

  /**
   * Outbound payout: shortcode -> customer handset.
   *
   * Two structural differences from initiateStkPush worth holding onto:
   *
   * 1. A "0" ResponseCode here means Safaricom ACCEPTED THE REQUEST INTO ITS QUEUE,
   *    not that money moved. The actual outcome arrives asynchronously at ResultURL.
   *    Nothing in this method's success path should ever be read as "the payout
   *    succeeded" — it means "the payout is now in flight."
   * 2. There are two callback URLs, not one. QueueTimeOutURL fires when Safaricom
   *    can't process the request in time; it explicitly does NOT mean the payout
   *    failed, and the handler for it must not release the reservation (see the
   *    b2c-timeout route).
   */
  async initiateB2C(creds: TenantPayoutCredentials, params: B2cParams): Promise<B2cResponse> {
    const accessToken = await this.getAccessToken(creds);

    const response = await fetch(`${this.baseUrl}/mpesa/b2c/v3/paymentrequest`, {
      method: "POST",
      headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        OriginatorConversationID: params.originatorConversationId,
        InitiatorName: creds.initiatorName,
        SecurityCredential: creds.securityCredential,
        CommandID: params.commandId,
        Amount: this.assertWholeShillings(params.amount, "for a B2C payout"),
        // PartyA is the paying shortcode and PartyB the receiving handset — the exact
        // reverse of the STK push above, where the customer is PartyA. Getting these
        // backwards is the single easiest mistake to make when adapting one to the other.
        PartyA: creds.shortcode,
        PartyB: params.msisdn,
        Remarks: params.remarks,
        QueueTimeOutURL: this.buildWebhookUrl("b2c-timeout"),
        ResultURL: this.buildWebhookUrl("b2c-result"),
        Occasion: params.occasion ?? "",
      }),
    });

    const body = await this.parseDarajaJson(response, "B2C payment");
    if (!response.ok || body.ResponseCode !== "0") {
      this.logger.error(`Daraja B2C request rejected: ${JSON.stringify(body)}`);
      // Same reasoning as initiateStkPush: Safaricom's rejection describes this
      // tenant's own request ("Invalid Initiator Information", "The initiator
      // information is invalid"), never another tenant's data, and is far more
      // actionable than the generic 500 a plain Error would collapse into.
      throw new BadGatewayException(
        body.errorMessage ?? body.ResponseDescription ?? "Daraja rejected the B2C payment request",
      );
    }

    return {
      ConversationID: body.ConversationID,
      // Echoed back by Safaricom. Returned rather than assumed so the caller can
      // assert it matches what it sent, if it ever wants to.
      OriginatorConversationID: body.OriginatorConversationID,
      ResponseCode: body.ResponseCode,
    };
  }

  /**
   * Confirms a tenant's consumer key/secret actually authenticate with Daraja,
   * without initiating any payment. Called right after a tenant submits credentials
   * so a typo surfaces immediately — as a rejected request — instead of silently
   * saving and only failing at the tenant's first real STK push. Reuses
   * getAccessToken's cache, so a push initiated shortly after doesn't pay for a
   * second OAuth round-trip.
   */
  async verifyCredentials(creds: DarajaAuthCredentials): Promise<void> {
    await this.getAccessToken(creds);
  }

  /**
   * One-time-per-shortcode call telling Safaricom where to deliver C2B callbacks for
   * payments that land on this shortcode WITHOUT going through STK Push (a customer
   * typing the Paybill number in directly, or paying a Till). Without this,
   * WebhookPollerService.processC2bConfirmation never receives anything to
   * process — Safaricom has no way to know this backend exists until told.
   *
   * ValidationURL is pointed at the same handler as ConfirmationURL: this backend
   * has no separate validation logic, and ResponseType "Completed" tells Safaricom
   * to auto-accept if Validation isn't enabled on this shortcode (the default) or if
   * ValidationURL can't be reached — so nothing here relies on that endpoint
   * distinguishing the two calls.
   */
  async registerC2bUrl(creds: C2bUrlRegistrationCredentials): Promise<void> {
    const accessToken = await this.getAccessToken(creds);
    const confirmationUrl = this.buildWebhookUrl("c2b-confirmation");

    const response = await fetch(`${this.baseUrl}/mpesa/c2b/v2/registerurl`, {
      method: "POST",
      headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        ShortCode: creds.shortcode,
        ResponseType: "Completed",
        ConfirmationURL: confirmationUrl,
        ValidationURL: confirmationUrl,
      }),
    });

    const body = await this.parseDarajaJson(response, "C2B URL registration");
    if (!response.ok || body.ResponseCode !== "0") {
      this.logger.error(`Daraja C2B URL registration rejected: ${JSON.stringify(body)}`);
      throw new BadGatewayException(
        body.errorMessage ?? body.ResponseDescription ?? "Daraja rejected C2B URL registration",
      );
    }
  }

  /**
   * Asks Safaricom for the outcome of an STK push. Returns `resultCode: null` when
   * they decline to say yet — see StkPushStatusResult for why that distinction is
   * load-bearing rather than pedantic.
   */
  async queryStkPushStatus(
    creds: TenantMpesaCredentials,
    checkoutRequestId: string,
  ): Promise<StkPushStatusResult> {
    const accessToken = await this.getAccessToken(creds);
    const { password, timestamp } = this.generatePassword(creds);

    const response = await fetch(`${this.baseUrl}/mpesa/stkpushquery/v1/query`, {
      method: "POST",
      headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        BusinessShortCode: creds.shortcode,
        Password: password,
        Timestamp: timestamp,
        CheckoutRequestID: checkoutRequestId,
      }),
    });

    const body = await this.parseDarajaJson(response, "STK push status query");

    // A verdict is a present, numeric ResultCode and nothing else. An in-flight push
    // (errorCode 500.001.1001), a throttled query, an expired token — all come back
    // without one, and every one of them means "ask again later", not "it failed".
    const rawResultCode = body.ResultCode;
    const parsed = rawResultCode === undefined || rawResultCode === null || rawResultCode === ""
      ? Number.NaN
      : Number(rawResultCode);

    if (!Number.isFinite(parsed)) {
      this.logger.log(
        `Daraja gave no verdict for CheckoutRequestID ${checkoutRequestId} ` +
          `(status ${response.status}, errorCode ${body.errorCode ?? "none"}): ${body.errorMessage ?? body.ResponseDescription ?? "no detail"}`,
      );
      return {
        resultCode: null,
        resultDesc: body.errorMessage ?? body.ResponseDescription,
        errorCode: body.errorCode,
      };
    }

    return { resultCode: parsed, resultDesc: body.ResultDesc };
  }
}
